apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  namespace: default
spec:
  ports:
  - name: order-service01
    port: 2003
    targetPort: order-service01
  selector:
    app: order-service